name: Shell commands

on: [push, pull_request]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "hello world howdy"
      - name: multi line script
        run: |
          node -v
          npm -v